name: Terraform Scan

# The scheduled workflow runs every day at 03:00 UTC time.
on:
  schedule:
  - cron: '0 3 * * *'

jobs:
  scan:
    name: Terraform Scheduled Scan
    uses:  crushten/github_workflow_repo/.github/workflows/terraform_scan.yml@main